---
- name: Load linux snap
  include_tasks:
    file: snap.yml
  args:
    apply:
      become: yes
      become_user: maxjerin
  tags:
    - linux

- name: Load linux apt
  include_tasks:
    file: apt.yml
  args:
    apply:
      become: yes
      become_user: maxjerin
  tags:
    - linux

- name: Load linux brew tasks
  include_tasks:
    file: chrome.yml
  args:
    apply:
      become: yes
      become_user: maxjerin
  tags:
    - linux
