---
- name: Add Notion-Enhancer (unofficial port of Notion to Linux) deb
  tags:
    - linux
  apt_repository:
    update_cache: true
    repo: deb [trusted=yes] https://apt.fury.io/notion-repackaged/ /
    state: present

- name: Install notion app
  tags:
    - linux
  apt:
    update_cache: true
    name:
      - notion-app-enhanced

- name: Install slack
  tags:
    - linux
  community.general.snap:
    name: slack
    state: present
    channel: latest/stable
    classic: true

- name: Install WhatsApp for Linux
  tags:
    - linux
  community.general.snap:
    name: whatsapp-for-linux
    state: present
    channel: latest/stable

- name: Add Google Chrome Signing Key
  tags:
    - linux
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  
- name: Add Google Chrome repository
  tags:
    - linux
  apt_repository:
    update_cache: true
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install Google Chrome
  tags:
    - linux
  apt:
    update_cache: true
    name:
      - google-chrome-stable

- name: Install Debian Utilities
  tags:
    - linux
  apt:
    update_cache: true
    name:
      - hardinfo
