---
- name: Load linux snap
  ansible.builtin.include_tasks:
    file: snap.yml
  args:
    apply:
      become: true
  tags:
    - linux

- name: Load linux apt
  ansible.builtin.include_tasks:
    file: apt.yml
  args:
    apply:
      become: true
  tags:
    - linux

- name: Load linux cursor and warp installation
  ansible.builtin.include_tasks:
    file: cursor-warp.yml
  args:
    apply:
      become: true
  tags:
    - linux

- name: Load linux brew tasks
  ansible.builtin.include_tasks:
    file: chrome.yml
  args:
    apply:
      become: true
  tags:
    - linux
