---
defaults:
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    name: Set very low key repeat rates
    type: int
    value: '25'
  - domain: NSGlobalDomain
    key: KeyRepeat
    name: Set very low key repeat rates
    type: int
    value: '1'
  - domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    name: Enable tap-to-click on Apple mouse
    type: int
    value: '1'
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: trackpadThreeFingerDrag
    name: Enable three finger drag
    type: int
    value: '1'
  - domain: com.apple.AppleBluetoothMultitouch
    key: trackpadThreeFingerDrag
    name: Enable three finger drag
    type: int
    value: '1'
  - domain: com.apple.finder
    key: autohide
    name: Auto-hide the Dock
    type: bool
    value: 'true'
