---
####### Deprecated ########
# https://github.com/petrstepanov/gnome-macos-remap
# - name: Install keyboard mapping tools
#   apt:
#     name:
#       - git
#       - autokey-gtk
#   # become: true
#   tags:
#     - linux

# - name: Download keybindgs repo
#   ansible.builtin.git:
#     repo: git@github.com:petrstepanov/gnome-macos-remap
#     dest: /tmp/gnome-macos-remap
#     version: 4850089
#   tags:
#     - linux

# - name: Add execute permission on files
#   ansible.builtin.file:
#     path: /tmp/gnome-macos-remap/install.sh
#     mode: u+rwx
#   tags:
#     - linux

# - name: Run keybindings script
#   command: /tmp/gnome-macos-remap/install.sh
#   changed_when: true
#   tags:
#     - linux

# - name: Install dependencies
#   apt:
#     name:
#       - dconf-cli
#       - dconf-editor
#       - dbus-x11
#   tags:
#     - linux

# - name: Copy keyboard config
#   copy:
#     src: pc.backup
#     dest: /usr/share/X11/xkb/symbols/pc

# - name: Run command to execute xkb mappings
#   ansible.builtin.command:
#     cmd: dconf write "/org/gnome/desktop/input-sources/xkb-options" "['caps:backspace', 'ctrl:swap_lalt_lctl', 'ctrl:swap_lctl_lalt']"
#   changed_when: true
#   become: true
#   become_method: sudo
#   tags:
#     - linux

####### Deprecated ########

- name: Ensure xkb keymap directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.xkb/keymap"
    state: directory
    mode: "0755"

- name: Ensure xkb keymap file exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.xkb/keymap/mykbd"
    state: touch
    mode: "0644"

- name: Generate xkb keymap
  ansible.builtin.shell: setxkbmap -print > "{{ ansible_env.HOME }}/.xkb/keymap/mykbd"
  args:
    creates: "{{ ansible_env.HOME }}/.xkb/keymap/mykbd"

- name: Ensure xkb symbols directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.xkb/symbols"
    state: directory
    mode: "0755"

- name: Copy keyboard config
  ansible.builtin.copy:
    src: custom_swap
    dest: ~/.xkb/symbols/custom_swap
    mode: "0644"

# TODO: figure out how to do this using sed
# https://unix.stackexchange.com/a/65600
# - name: Inject custom swap defintion into ~/xkb/keymap/mykbd
# +custom_swap(swap_definition) needs to be appended to xkb_symbols
# xkb_symbols   { include "pc+us+us:2+inet(evdev)+custom_swap(swap_definition)"	};


- name: Output current keyboard defintion (disble warnings)
  # applies keymap each run by design (no reliable state probe)
  ansible.builtin.command:
    cmd: xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/mykbd $DISPLAY
  changed_when: true
