---
- name: Load macos
  include_tasks:
    file: macos.yml
  tags:
    - macos

- name: Load linux
  include_tasks:
    file: linux.yml
  args:
    apply:
      become: yes
      become_method: sudo
  tags:
    - linux
