---
- name: Load macos
  ansible.builtin.include_tasks:
    file: macos.yml
  tags:
    - macos

- name: Load linux
  ansible.builtin.include_tasks:
    file: linux.yml
  args:
    apply:
      become: true
      become_method: sudo
  tags:
    - linux
