---
- name: Import signing key
  apt_key:
    file: /ansible-managed/google-chrome/linux_signing_key.pub
    keyring: /etc/apt/trusted.gpg.d/google.gpg
  when: public_key.changed
  register: key

- name: Add Google Chrome package source
  copy:
    src: google-chrome.list
    dest: /etc/apt/sources.list.d/
  register: source

- name: Test "apt-get update"
  command: apt-get update
  when: key.changed or source.changed
  register: update
  failed_when: update.rc != 0 or update.stderr != ""
  args:
    warn: false  # Can't use apt module.  It doesn't detect unreachable repos.

- name: Test package is available in repo
  command: apt-get --print-uris download google-chrome-stable
  args:
    warn: false  # can't use ansible apt module, it does not implement this
  check_mode: false
  changed_when: false

- name: Install Google Chrome
  package:
    name: google-chrome-stable
    state: present
