#!/bin/bash

#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

#
# #1 Non-ASCII filename check
#
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

#
# #2 Encrypt before committing
#
if ! command -v ansible-vault &> /dev/null
then
	echo "ansible-vault not installed, cannot encrypt before commit"
	exit 1
fi

PASSWORD_FILE="$(pwd)/.vault-password"
printf "Encrypting file in pre-commit %s\n" "$(pwd)/dotfile_templates/zsh/zsh/abbreviations_work"
FILE_TO_ENCRYPT="$(pwd)/dotfile_templates/zsh/zsh/abbreviations_work"
head -1 "$FILE_TO_ENCRYPT" | grep --quiet "^\$ANSIBLE_VAULT;" && ansible-vault encrypt "${FILE_TO_ENCRYPT}" --vault-password-file "${PASSWORD_FILE}"

CURR_DIR="$(pwd)/Raycast"
pushd "$CURR_DIR" || exit
for i in $(find . -type f); do
	printf "Encrypting file in pre-commit %s \n" "${CURR_DIR}/${i}"
	head -1 "${i}" | grep --quiet "^\$ANSIBLE_VAULT;" && ansible-vault encrypt "$i" --vault-password-file "${PASSWORD_FILE}";
done
popd || exit

#
# #3 Whitespace error
#
# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
