---
- name: Add universe repositroy
  ansible.builtin.apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
    state: present

- name: Install Fonts
  ansible.builtin.apt:
    name:
      - fonts-firacode
      - fonts-roboto
    state: present

# https://swetankraj.github.io/ubuntu-terminal-powelinego/
- name: Download Powerline Symbols
  ansible.builtin.get_url:
    url: https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
    dest: /tmp/PowerlineSymbols.otf
    mode: "0644"
  changed_when: false
# checksum: figure out how to do this?

- name: Download 10-powerline-symbols
  ansible.builtin.get_url:
    url: https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
    dest: /tmp/10-powerline-symbols.conf
    mode: "0644"
  changed_when: false
# checksum: figure out how to do this?

- name: Set Powerline source dir
  ansible.builtin.set_fact:
    powerline_src_dir: /tmp

- name: Install Powerline symbols font
  ansible.builtin.copy:
    src: "{{ powerline_src_dir }}/PowerlineSymbols.otf"
    dest: /usr/share/fonts/PowerlineSymbols.otf
    remote_src: true
    mode: "0644"
  become: true

- name: Install Powerline fontconfig
  ansible.builtin.copy:
    src: "{{ powerline_src_dir }}/10-powerline-symbols.conf"
    dest: /etc/fonts/conf.d/10-powerline-symbols.conf
    remote_src: true
    mode: "0644"
  become: true

- name: Refresh font cache
  ansible.builtin.command:
    cmd: fc-cache -vf /usr/share/fonts
  changed_when: true
  become: true
